title: Home
decluttering_templates: !include_dir_merge_named ui/shared/templates
button_card_templates: !include ui/shared/templates/button_card_templates.yaml

views:
  - !include ui/overview.yaml
  - !include ui/wohnzimmer/wohnzimmer.yaml
  - !include ui/arbeitszimmer/arbeitszimmer.yaml
  - !include ui/diele_og/diele_og.yaml
  - !include ui/kueche/kueche.yaml
  - !include ui/waschkeller/waschkeller.yaml
  - !include ui/garten/garten.yaml
  - !include ui/oelkeller/oelkeller.yaml
