title: Home
decluttering_templates: !include ui/shared/decluttering_templates.yaml
views:
  - !include ui/overview.yaml
  - !include ui/wohnzimmer/wohnzimmer.yaml
  - !include ui/kueche/kueche.yaml
  - !include ui/waschkeller/waschkeller.yaml
  - !include ui/garten/garten.yaml
  - !include ui/oelkeller/oelkeller.yaml
